### ISSUE TITLE
Consider testMode in place of/as well as useProduction

### ISSUE THREAD

**Issue by judgej** [Transportersio/omnipay-judopay#1]
Omnipay Core already has a `testMode` parameter that many frameworks can set. `true` uses the test gateway and `false` uses production (so the opposite of `useProduction`).

Maybe keep the `useProduction` parameter, but the `testMode` parameter can be a wrapper for it.

**Comment by mnwalker** [comment]
Fixed with https://github.com/Transportersio/omnipay-judopay/commit/be35b214c873358099e263eb926fbd7f6d905465
